### ISSUE TITLE
Add Jekyll docker image for easy local development

### ISSUE THREAD

**Issue by mschilling** [move4mobile/move4mobile.github.io#13]
Add Jekyll Docker image (using docker-compose.yml file) for making local development as easy as possible. 

We all should not spent too much time on setting up die Jekyll local environment over and over again.

**Comment by wwolters** [comment]
Fixed by https://github.com/move4mobile/move4mobile.github.io/commit/fa99a6a563ca0c57d7912e76cf58fef5d1f46982
