### ISSUE TITLE
No comments indication in Title

### ISSUE THREAD

**Issue by rubenaalders** [move4mobile/move4mobile.github.io#17]
There is no indication about how many people have replied on [this](https://geekbites.move4mobile.io/2017/03/22/hololens/) post.

**Comment by wwolters** [comment]
https://geekbites.move4mobile.io/2017/01/18/tribute-to-fieldset/ misses the indication as well.

**Comment by wwolters** [comment]
... because it does not have comments

**Comment by wwolters** [comment]
Working now, Disqus seems slow today.
