### ISSUE TITLE
Embed Travis CI status image

### ISSUE THREAD

**Issue by 0x1ad2** [move4mobile/move4mobile.github.io#7]
![badge](http://s3itch.paperplanes.de/statusimage_20140320_112129.jpg)

https://docs.travis-ci.com/user/status-images/

**Comment by mschilling** [comment]
Ok, will set `develop` build status as default.

**Comment by m4mwilco** [comment]
The badge added is for master

**Comment by mschilling** [comment]
You're right :-)
